In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.drop("User_ID",axis=1)

In [5]:
indepCols=dataset[["Age","EstimatedSalary","Gender_Male"]]
depCols=dataset["Purchased"]

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(indepCols, depCols, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1')  
   
# fitting the model for grid search 
# fitting the model for grid search 
grid.fit(x_train, y_train) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\tpous\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\tpous\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tpous\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Use

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [10]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test) 



In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [12]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)


In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9256751954513149


In [14]:
print(cm)

[[79  6]
 [ 4 45]]


In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134



In [16]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9256751954513149


In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
print(x_test)

[[-0.76605872  0.52531653  1.00754728]
 [ 0.02298918 -0.57354963 -0.99250926]
 [-0.27290378  0.16892751  1.00754728]
 [-0.76605872  0.28772385 -0.99250926]
 [-0.27290378 -0.57354963 -0.99250926]
 [-1.06195168 -1.4645222   1.00754728]
 [-0.66742773 -1.61301763 -0.99250926]
 [-0.1742728   2.21816441  1.00754728]
 [-1.94963056 -0.03896609 -0.99250926]
 [ 0.91066806 -0.78144323  1.00754728]
 [-0.76605872 -0.60324872  1.00754728]
 [-0.96332069 -0.42505421 -0.99250926]
 [-0.07564181 -0.42505421  1.00754728]
 [ 0.12162016  0.22832568  1.00754728]
 [-1.75236858  0.49561745  1.00754728]
 [-0.56879674  1.4162891  -0.99250926]
 [-0.07564181  0.22832568  1.00754728]
 [-1.85099957  0.46591836  1.00754728]
 [ 1.69971595  1.80237721 -0.99250926]
 [-0.27290378 -1.40512403  1.00754728]
 [-0.27290378 -0.66264689 -0.99250926]
 [ 0.91066806  2.21816441 -0.99250926]
 [ 0.31888214 -0.54385055 -0.99250926]
 [ 0.91066806  1.05990007  1.00754728]
 [-1.45647562 -1.22692951 -0.99250926]
 [ 1.10793003  2.12906715

In [21]:
table_pr=pd.DataFrame()

table_pr['Age']=x_test[1]
table_pr['Gender_male']=x_test[2]
table_pr['Estimated_Salary']=x_test[3]
table_pr['Actual']=y_test
#table_pr['Predicted']=grid_predictions

In [22]:
table_pr.head(134)

Age  Gender_male  Estimated_Salary  Actual
0  0.022989    -0.272904         -0.766059     NaN
1 -0.573550     0.168928          0.287724     0.0
2 -0.992509     1.007547         -0.992509     NaN

In [23]:
table_pr.to_csv("cm.csv",index=False)
